name: Check Makefiles

on:
  push:
    branches:
      - main
    paths:
      - "**/*Makefile*"
      - ".config/checkmake"
      - ".github/workflows/checkmake.yaml"
  pull_request:
    paths:
      - "**/*Makefile*"
      - ".config/checkmake"
      - ".github/workflows/checkmake.yaml"

jobs:
  checkmake:
    name: Check Makefile Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417  # v6.3.0
        with:
          go-version: "1.26"
      - run: go install github.com/checkmake/checkmake/cmd/checkmake@latest
      - run: checkmake --config .config/checkmake Makefile
